### ISSUE TITLE
[Bug]: Incompatible Versions

### ISSUE THREAD

**Issue by user3470** [beyondcode/laravel-ask-database#1]
### What happened?

When I try to install I'm getting this error

```sh
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires beyondcode/laravel-ask-database ^1.0 -> satisfiable by beyondcode/laravel-ask-database[1.0.0].
    - beyondcode/laravel-ask-database 1.0.0 requires doctrine/dbal ^3.6 -> found doctrine/dbal[3.6.0, 3.6.x-dev] but the package is fixed to 2.13.9 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require beyondcode/laravel-ask-database:*" to figure out if any version is installable, or "composer require beyondcode/laravel-ask-database:^2.1" if you know which you need.
```

### How to reproduce the bug

`composer require beyondcode/laravel-ask-database`

On Laravel version 9.19

### Package Version

1

### PHP Version

8.1.2

### Laravel Version

9.19

### Which operating systems does with happen with?

Linux

**Comment by tovitch** [comment]
You can try

`composer require beyondcode/laravel-ask-database --with-all-dependencies`

**Comment by eduardocruz** [comment]
If the code above does not work for whatever reason, you can try updating the composer.json file to: 
` "doctrine/dbal": "^3.0",`  and see what happens.

**Comment by Mirmuxsin** [comment]
> If the code above does not work for whatever reason, you can try updating the composer.json file to: ` "doctrine/dbal": "^3.0",` and see what happens.

worked for me, thanks
