### ISSUE TITLE
[Bug]: Package should probably be marked as abandoned?

### ISSUE THREAD

**Issue by DanWithams** [beyondcode/laravel-ask-database#15]
### What happened?

Package tries to use a depreciated model;
```php
'model' => 'text-davinci-003',
```
This setting is unable to be changed by any config
```
OpenAI\Exceptions\ErrorException 

The model `text-davinci-  003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations
```
Package has not been updated in a long time and users' bugs reports an queries have gone unattended for months.

### How to reproduce the bug

Inherant problem with the package

### Package Version

1.0.0

### PHP Version

8.2.0

### Laravel Version

10.0.0

### Which operating systems does with happen with?

macOS, Windows, Linux

### Notes

Package tries to use a depreciated model;
```php
'model' => 'text-davinci-003',
```
This setting is unable to be changed by any config
```
OpenAI\Exceptions\ErrorException 

The model `text-davinci-  003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations
```
Package has not been updated in a long time and users' bugs reports an queries have gone unattended for months.

**Comment by DanWithams** [comment]
Hope the above helps anyone else struggling to use this package.

**Comment by mpociot** [comment]
Yeah, this package was more meant to be a "prototype" and an example of how this can be done with OpenAI rather than turning this into a production-use package (also given the nature of evaluating AI-generated SQL queries).
