### ISSUE TITLE
creating join query

### ISSUE THREAD

**Issue by haythoo** [beyondcode/laravel-ask-database#3]
### What happened?

Hi,
Thanks for this great repo!

Do you plan to support generating queries from multiple tables?

### How to reproduce the bug

For example, if I have a countries table and a cities table, I would be asking this question:

`DB::ask('How many city in USA?');`

Currently, it is not working:

` Illuminate\Database\QueryException  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'country' in 'where clause' (SQL: SELECT COUNT(*) FROM cities WHERE country = 'USA';).`

### Package Version

1.0

### PHP Version

8.1

### Laravel Version

9

### Which operating systems does with happen with?

Windows

**Comment by pathros** [comment]
Maybe you can try to improve the prompt in [this file](https://github.com/beyondcode/laravel-ask-database/blob/main/resources/views/prompts/tables.blade.php) and submit a PR ...
