### ISSUE TITLE
[Bug]: Unknown database type enum requested

### ISSUE THREAD

**Issue by liran-co** [beyondcode/laravel-ask-database#6]
### What happened?

Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

### How to reproduce the bug

1. Install the package
2. Run `$answer = DB::ask('How many users do we have?');`

### Package Version

1.0

### PHP Version

8.2.0

### Laravel Version

9

**Comment by nathanheffley** [comment]
For a short term fix, putting this before you run the `ask` function should get it to run:

```
// @see https://github.com/doctrine/dbal/issues/3161#issuecomment-542814085
DB::connection()->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
```

The GitHub issue I found the answer in has some technical info.

**Comment by Rignesh-EWW** [comment]
> ### What happened?
> Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
> 
> ### How to reproduce the bug
> 1. Install the package
> 2. Run `$answer = DB::ask('How many users do we have?');`
> 
> ### Package Version
> 1.0
> 
> ### PHP Version
> 8.2.0
> 
> ### Laravel Version
> 9
> 
> ### Which operating systems does with happen with?
> _No response_
> 
> ### Notes
> _No response_

https://github.com/beyondcode/laravel-ask-database/issues/17#issuecomment-1916087112

`DB::connection()->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');`

**Comment by nathanheffley** [comment]
Thanks @Rignesh-EWW , although this ticket does appear dead as I already commented that same solution quite a while ago with no response 😄
